# Site settings
title: Melissa Auclaire
description: Jekyll Theme Minimal Resume # http://willianjusten.com.br
#baseurl: "/portfolio_website" # the subpath of your site, e.g. /blog
#url: "rhapsodyai.github.io"

# User settings
username: Melissa Auclaire
user_description: I'm a full-stack web developer who has worked primarily with Ruby on Rails and Django. I have 3 years of experience in the tech industry, mostly working with small startups (not including my own). I'm both an international and keynote speaker and speak occasionally about my work. Above all, I enjoy coding, making art and games!
user_title: Software Engineer
email: rhapsody.ai@gmail.com
twitter_username: kiyomizumia
github_username:  rhapsodyai


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
